server:
  port: 9898

spring:
  rabbitmq:
    host: localhost  # RabbitMQ host adresi
    port: 5672       # RabbitMQ varsayılan portu
    username: guest  # RabbitMQ kullanıcı adı
    password: guest  # RabbitMQ şifresi